### ISSUE TITLE
akka example not working

### ISSUE THREAD

**Issue by mfirry** [avibryant/bazel-scala-example#4]
I'm sort of stuck again here: https://github.com/mfirry/b-test-akka

What am I doing wrong?

**Comment by mfirry** [comment]
Paging @johnynek for a little help! :)

**Comment by oscar-stripe** [comment]
sorry for the delay. Can you post what your symtoms are?

what does `bazel build //...` do?

**Comment by mfirry** [comment]
```
╰─$ bazel build example-bin
...............................................................
ERROR: /Users/mfirry/personal/b-test-akka/3rdparty/jvm/com/typesafe/akka/BUILD:1:1: name 'scala_library' is not defined (did you mean 'java_library'?).
ERROR: /Users/mfirry/personal/b-test-akka/BUILD:3:1: no such target '//3rdparty/jvm/com/typesafe/akka:akka_actor': target 'akka_actor' not declared in package '3rdparty/jvm/com/typesafe/akka' defined by /Users/mfirry/personal/b-test-akka/3rdparty/jvm/com/typesafe/akka/BUILD and referenced by '//:example-bin'.
ERROR: Analysis of target '//:example-bin' failed; build aborted.
INFO: Elapsed time: 7.205s
```

**Comment by johnynek** [comment]
@mfirry ahh... so, you can use a later version of the bazel deps too to add `load(...., "scala_library")` to each BUILD file, or you can add:

```
load("@io_bazel_rules_scala//scala:scala.bzl",
  "scala_library", "scala_macro_library", "scala_binary", "scala_test", "scala_repl")
```
to `tools/build_rules/prelude_bazel`

**Comment by mfirry** [comment]
Trying it out. Will keep you posted. Thanks!

**Comment by mfirry** [comment]
Ok it works now. 
Although I had to manually add the `load(...` part. 
The newest `bazel-deps` did not seem to change much.
Thanks again!

**Comment by johnynek** [comment]
You have to manually add the load header as an option. I can show you how
when I get back to my machine.

**Comment by oscar-stripe** [comment]
I didn't document it yet, but in you bazel-deps yaml file you can add `options:` you can put a `buildHeader` which is a list of strings:
```
options:
  buildHeader:
    - load("foo", "baz", "bar")
    - "# some comment even!!"
```

I think that should get it fixed.

**Comment by oscar-stripe** [comment]
https://github.com/johnynek/bazel-deps/blob/master/src/scala/com/github/johnynek/bazel_deps/DepsModel.scala#L641

**Comment by oscar-stripe** [comment]
https://github.com/johnynek/bazel-deps/pull/37

there you go.
